export interface CountryInfo {
  code: string;
  name: string;
  nativeName?: string;
  region: string;
  flag: string;
  type?: 'Country' | 'Territory' | 'Autonomous' | 'Disputed' | 'Special';
}

export const COUNTRIES: CountryInfo[] = [
  // East Asia
  { code: 'JP', name: 'Japan', nativeName: '日本', region: 'East Asia', flag: '🇯🇵' },
  { code: 'CN', name: 'China', nativeName: '中国', region: 'East Asia', flag: '🇨🇳' },
  { code: 'KR', name: 'South Korea', nativeName: '대한민국', region: 'East Asia', flag: '🇰🇷' },
  { code: 'TW', name: 'Taiwan', nativeName: '台灣', region: 'East Asia', flag: '🇹🇼', type: 'Autonomous' },
  { code: 'HK', name: 'Hong Kong', nativeName: '香港', region: 'East Asia', flag: '🇭🇰', type: 'Autonomous' },
  { code: 'MO', name: 'Macau', nativeName: '澳門', region: 'East Asia', flag: '🇲🇴', type: 'Autonomous' },
  { code: 'MN', name: 'Mongolia', nativeName: 'Монгол улス', region: 'East Asia', flag: '🇲🇳' },
  { code: 'KP', name: 'North Korea', nativeName: '조선민주주의인민공화국', region: 'East Asia', flag: '🇰🇵' },

  // Southeast Asia
  { code: 'TH', name: 'Thailand', nativeName: 'ประเทศไทย', region: 'Southeast Asia', flag: '🇹🇭' },
  { code: 'ID', name: 'Indonesia', nativeName: 'Indonesia', region: 'Southeast Asia', flag: '🇮🇩' },
  { code: 'VN', name: 'Vietnam', nativeName: 'Việt Nam', region: 'Southeast Asia', flag: '🇻🇳' },
  { code: 'MY', name: 'Malaysia', nativeName: 'Malaysia', region: 'Southeast Asia', flag: '🇲🇾' },
  { code: 'PH', name: 'Philippines', nativeName: 'Pilipinas', region: 'Southeast Asia', flag: '🇵🇭' },
  { code: 'SG', name: 'Singapore', nativeName: 'Singapore', region: 'Southeast Asia', flag: '🇸🇬' },
  { code: 'MM', name: 'Myanmar', nativeName: 'မြန်မာ', region: 'Southeast Asia', flag: '🇲🇲' },
  { code: 'KH', name: 'Cambodia', nativeName: 'កម្ពុជា', region: 'Southeast Asia', flag: '🇰🇭' },
  { code: 'LA', name: 'Laos', nativeName: 'ລາວ', region: 'Southeast Asia', flag: '🇱🇦' },
  { code: 'BN', name: 'Brunei', nativeName: 'Brunei', region: 'Southeast Asia', flag: '🇧🇳' },
  { code: 'TL', name: 'Timor-Leste', nativeName: 'Timor-Leste', region: 'Southeast Asia', flag: '🇹🇱' },

  // South Asia
  { code: 'IN', name: 'India', nativeName: 'India', region: 'South Asia', flag: '🇮🇳' },
  { code: 'PK', name: 'Pakistan', nativeName: 'Pakistan', region: 'South Asia', flag: '🇵🇰' },
  { code: 'BD', name: 'Bangladesh', nativeName: 'Bangladesh', region: 'South Asia', flag: '🇧🇩' },
  { code: 'LK', name: 'Sri Lanka', nativeName: 'Sri Lanka', region: 'South Asia', flag: '🇱🇰' },
  { code: 'NP', name: 'Nepal', nativeName: 'Nepal', region: 'South Asia', flag: '🇳🇵' },
  { code: 'BT', name: 'Bhutan', nativeName: 'Bhutan', region: 'South Asia', flag: '🇧🇹' },
  { code: 'MV', name: 'Maldives', nativeName: 'Maldives', region: 'South Asia', flag: '🇲🇻' },
  { code: 'AF', name: 'Afghanistan', nativeName: 'افغانستان', region: 'South Asia', flag: '🇦🇫' },

  // North America
  { code: 'US', name: 'United States', nativeName: 'United States', region: 'North America', flag: '🇺🇸' },
  { code: 'CA', name: 'Canada', nativeName: 'Canada', region: 'North America', flag: '🇨🇦' },
  { code: 'MX', name: 'Mexico', nativeName: 'México', region: 'North America', flag: '🇲🇽' },
  { code: 'GL', name: 'Greenland', nativeName: 'Kalaallit Nunaat', region: 'North America', flag: '🇬🇱', type: 'Territory' },
  { code: 'PM', name: 'Saint Pierre and Miquelon', nativeName: 'Saint-Pierre-et-Miquelon', region: 'North America', flag: '🇵🇲', type: 'Territory' },
  { code: 'BM', name: 'Bermuda', nativeName: 'Bermuda', region: 'North America', flag: '🇧🇲', type: 'Territory' },

  // Central America & Caribbean
  { code: 'GT', name: 'Guatemala', nativeName: 'Guatemala', region: 'Central America', flag: '🇬🇹' },
  { code: 'BZ', name: 'Belize', nativeName: 'Belize', region: 'Central America', flag: '🇧🇿' },
  { code: 'SV', name: 'El Salvador', nativeName: 'El Salvador', region: 'Central America', flag: '🇸🇻' },
  { code: 'HN', name: 'Honduras', nativeName: 'Honduras', region: 'Central America', flag: '🇭🇳' },
  { code: 'NI', name: 'Nicaragua', nativeName: 'Nicaragua', region: 'Central America', flag: '🇳🇮' },
  { code: 'CR', name: 'Costa Rica', nativeName: 'Costa Rica', region: 'Central America', flag: '🇨🇷' },
  { code: 'PA', name: 'Panama', nativeName: 'Panamá', region: 'Central America', flag: '🇵🇦' },
  { code: 'CU', name: 'Cuba', nativeName: 'Cuba', region: 'Caribbean', flag: '🇨🇺' },
  { code: 'JM', name: 'Jamaica', nativeName: 'Jamaica', region: 'Caribbean', flag: '🇯🇲' },
  { code: 'HT', name: 'Haiti', nativeName: 'Haïti', region: 'Caribbean', flag: '🇭🇹' },
  { code: 'DO', name: 'Dominican Republic', nativeName: 'República Dominicana', region: 'Caribbean', flag: '🇩🇴' },
  { code: 'PR', name: 'Puerto Rico', nativeName: 'Puerto Rico', region: 'Caribbean', flag: '🇵🇷', type: 'Territory' },
  { code: 'BS', name: 'Bahamas', nativeName: 'Bahamas', region: 'Caribbean', flag: '🇧🇸' },
  { code: 'AW', name: 'Aruba', nativeName: 'Aruba', region: 'Caribbean', flag: '🇦🇼', type: 'Autonomous' },
  { code: 'CW', name: 'Curaçao', nativeName: 'Curaçao', region: 'Caribbean', flag: '🇨🇼', type: 'Autonomous' },
  { code: 'SX', name: 'Sint Maarten', nativeName: 'Sint Maarten', region: 'Caribbean', flag: '🇸🇽', type: 'Autonomous' },
  { code: 'BQ', name: 'Caribbean Netherlands', nativeName: 'Caribisch Nederland', region: 'Caribbean', flag: '🇧🇶', type: 'Territory' },
  { code: 'GP', name: 'Guadeloupe', nativeName: 'Guadeloupe', region: 'Caribbean', flag: '🇬🇵', type: 'Territory' },
  { code: 'MQ', name: 'Martinique', nativeName: 'Martinique', region: 'Caribbean', flag: '🇲🇶', type: 'Territory' },
  { code: 'MF', name: 'Saint Martin', nativeName: 'Saint-Martin', region: 'Caribbean', flag: '🇲🇫', type: 'Territory' },
  { code: 'BL', name: 'Saint Barthélemy', nativeName: 'Saint-Barthélemy', region: 'Caribbean', flag: '🇧🇱', type: 'Territory' },
  { code: 'BB', name: 'Barbados', nativeName: 'Barbados', region: 'Caribbean', flag: '🇧🇧' },
  { code: 'TT', name: 'Trinidad and Tobago', nativeName: 'Trinidad and Tobago', region: 'Caribbean', flag: '🇹🇹' },
  { code: 'DM', name: 'Dominica', nativeName: 'Dominica', region: 'Caribbean', flag: '🇩🇲' },
  { code: 'LC', name: 'Saint Lucia', nativeName: 'Saint Lucia', region: 'Caribbean', flag: '🇱🇨' },
  { code: 'VC', name: 'Saint Vincent and the Grenadines', nativeName: 'Saint Vincent and the Grenadines', region: 'Caribbean', flag: '🇻🇨' },
  { code: 'GD', name: 'Grenada', nativeName: 'Grenada', region: 'Caribbean', flag: '🇬🇩' },
  { code: 'AG', name: 'Antigua and Barbuda', nativeName: 'Antigua and Barbuda', region: 'Caribbean', flag: '🇦🇬' },
  { code: 'KN', name: 'Saint Kitts and Nevis', nativeName: 'Saint Kitts and Nevis', region: 'Caribbean', flag: '🇰🇳' },
  { code: 'VG', name: 'British Virgin Islands', nativeName: 'British Virgin Islands', region: 'Caribbean', flag: '🇻🇬', type: 'Territory' },
  { code: 'KY', name: 'Cayman Islands', nativeName: 'Cayman Islands', region: 'Caribbean', flag: '🇰🇾', type: 'Territory' },
  { code: 'MS', name: 'Montserrat', nativeName: 'Montserrat', region: 'Caribbean', flag: '🇲🇸', type: 'Territory' },
  { code: 'TC', name: 'Turks and Caicos Islands', nativeName: 'Turks and Caicos Islands', region: 'Caribbean', flag: '🇹🇨', type: 'Territory' },
  { code: 'AI', name: 'Anguilla', nativeName: 'Anguilla', region: 'Caribbean', flag: '🇦🇮', type: 'Territory' },

  // South America
  { code: 'BR', name: 'Brazil', nativeName: 'Brasil', region: 'South America', flag: '🇧🇷' },
  { code: 'AR', name: 'Argentina', nativeName: 'Argentina', region: 'South America', flag: '🇦🇷' },
  { code: 'CL', name: 'Chile', nativeName: 'Chile', region: 'South America', flag: '🇨🇱' },
  { code: 'CO', name: 'Colombia', nativeName: 'Colombia', region: 'South America', flag: '🇨🇴' },
  { code: 'PE', name: 'Peru', nativeName: 'Perú', region: 'South America', flag: '🇵🇪' },
  { code: 'VE', name: 'Venezuela', nativeName: 'Venezuela', region: 'South America', flag: '🇻🇪' },
  { code: 'EC', name: 'Ecuador', nativeName: 'Ecuador', region: 'South America', flag: '🇪🇨' },
  { code: 'BO', name: 'Bolivia', nativeName: 'Bolivia', region: 'South America', flag: '🇧🇴' },
  { code: 'PY', name: 'Paraguay', nativeName: 'Paraguay', region: 'South America', flag: '🇵🇾' },
  { code: 'UY', name: 'Uruguay', nativeName: 'Uruguay', region: 'South America', flag: '🇺🇾' },
  { code: 'GY', name: 'Guyana', nativeName: 'Guyana', region: 'South America', flag: '🇬🇾' },
  { code: 'SR', name: 'Suriname', nativeName: 'Suriname', region: 'South America', flag: '🇸🇷' },
  { code: 'GF', name: 'French Guiana', nativeName: 'Guyane française', region: 'South America', flag: '🇬🇫', type: 'Territory' },
  { code: 'FK', name: 'Falkland Islands', nativeName: 'Falkland Islands', region: 'South America', flag: '🇫🇰', type: 'Territory' },
  { code: 'GS', name: 'South Georgia', nativeName: 'South Georgia', region: 'South America', flag: '🇬🇸', type: 'Territory' },

  // Europe
  { code: 'GB', name: 'United Kingdom', nativeName: 'United Kingdom', region: 'Europe', flag: '🇬🇧' },
  { code: 'FR', name: 'France', nativeName: 'France', region: 'Europe', flag: '🇫🇷' },
  { code: 'DE', name: 'Germany', nativeName: 'Deutschland', region: 'Europe', flag: '🇩🇪' },
  { code: 'IT', name: 'Italy', nativeName: 'Italia', region: 'Europe', flag: '🇮🇹' },
  { code: 'ES', name: 'Spain', nativeName: 'España', region: 'Europe', flag: '🇪🇸' },
  { code: 'NL', name: 'Netherlands', nativeName: 'Nederland', region: 'Europe', flag: '🇳🇱' },
  { code: 'BE', name: 'Belgium', nativeName: 'België', region: 'Europe', flag: '🇧🇪' },
  { code: 'CH', name: 'Switzerland', nativeName: 'Schweiz', region: 'Europe', flag: '🇨🇭' },
  { code: 'AT', name: 'Austria', nativeName: 'Österreich', region: 'Europe', flag: '🇦🇹' },
  { code: 'SE', name: 'Sweden', nativeName: 'Sverige', region: 'Europe', flag: '🇸🇪' },
  { code: 'NO', name: 'Norway', nativeName: 'Norge', region: 'Europe', flag: '🇳🇴' },
  { code: 'DK', name: 'Denmark', nativeName: 'Danmark', region: 'Europe', flag: '🇩🇰' },
  { code: 'FI', name: 'Finland', nativeName: 'Suomi', region: 'Europe', flag: '🇫🇮' },
  { code: 'IE', name: 'Ireland', nativeName: 'Éire', region: 'Europe', flag: '🇮🇪' },
  { code: 'PT', name: 'Portugal', nativeName: 'Portugal', region: 'Europe', flag: '🇵🇹' },
  { code: 'GR', name: 'Greece', nativeName: 'Ελλάδα', region: 'Europe', flag: '🇬🇷' },
  { code: 'RU', name: 'Russia', nativeName: 'Россия', region: 'Europe', flag: '🇷🇺' },
  { code: 'UA', name: 'Ukraine', nativeName: 'Україна', region: 'Europe', flag: '🇺🇦' },
  { code: 'PL', name: 'Poland', nativeName: 'Polska', region: 'Europe', flag: '🇵🇱' },
  { code: 'CZ', name: 'Czech Republic', nativeName: 'Česko', region: 'Europe', flag: '🇨🇿' },
  { code: 'HU', name: 'Hungary', nativeName: 'Magyarország', region: 'Europe', flag: '🇭🇺' },
  { code: 'RO', name: 'Romania', nativeName: 'România', region: 'Europe', flag: '🇷🇴' },
  { code: 'TR', name: 'Turkey', nativeName: 'Türkiye', region: 'Europe', flag: '🇹🇷' },
  { code: 'IS', name: 'Iceland', nativeName: 'Ísland', region: 'Europe', flag: '🇮🇸' },
  { code: 'EE', name: 'Estonia', nativeName: 'Eesti', region: 'Europe', flag: '🇪🇪' },
  { code: 'LV', name: 'Latvia', nativeName: 'Latvija', region: 'Europe', flag: '🇱🇻' },
  { code: 'LT', name: 'Lithuania', nativeName: 'Lietuva', region: 'Europe', flag: '🇱🇹' },
  { code: 'BY', name: 'Belarus', nativeName: 'Беларусь', region: 'Europe', flag: '🇧🇾' },
  { code: 'MD', name: 'Moldova', nativeName: 'Moldova', region: 'Europe', flag: '🇲🇩' },
  { code: 'BG', name: 'Bulgaria', nativeName: 'България', region: 'Europe', flag: '🇧🇬' },
  { code: 'SK', name: 'Slovakia', nativeName: 'Slovensko', region: 'Europe', flag: '🇸🇰' },
  { code: 'HR', name: 'Croatia', nativeName: 'Hrvatska', region: 'Europe', flag: '🇭🇷' },
  { code: 'RS', name: 'Serbia', nativeName: 'Србија', region: 'Europe', flag: '🇷🇸' },
  { code: 'BA', name: 'Bosnia and Herzegovina', nativeName: 'BiH', region: 'Europe', flag: '🇧🇦' },
  { code: 'AL', name: 'Albania', nativeName: 'Shqipëria', region: 'Europe', flag: '🇦🇱' },
  { code: 'MK', name: 'North Macedonia', nativeName: 'Северна Македонија', region: 'Europe', flag: '🇲🇰' },
  { code: 'SI', name: 'Slovenia', nativeName: 'Slovenija', region: 'Europe', flag: '🇸🇮' },
  { code: 'ME', name: 'Montenegro', nativeName: 'Crna Gora', region: 'Europe', flag: '🇲🇪' },
  { code: 'LU', name: 'Luxembourg', nativeName: 'Luxembourg', region: 'Europe', flag: '🇱🇺' },
  { code: 'MT', name: 'Malta', nativeName: 'Malta', region: 'Europe', flag: '🇲🇹' },
  { code: 'CY', name: 'Cyprus', nativeName: 'Κύπρος', region: 'Europe', flag: '🇨🇾' },
  { code: 'AD', name: 'Andorra', nativeName: 'Andorra', region: 'Europe', flag: '🇦🇩' },
  { code: 'MC', name: 'Monaco', nativeName: 'Monaco', region: 'Europe', flag: '🇲🇨' },
  { code: 'LI', name: 'Liechtenstein', nativeName: 'Liechtenstein', region: 'Europe', flag: '🇱🇮' },
  { code: 'SM', name: 'San Marino', nativeName: 'San Marino', region: 'Europe', flag: '🇸🇲' },
  { code: 'VA', name: 'Vatican City', nativeName: 'Vaticano', region: 'Europe', flag: '🇻🇦' },
  { code: 'JE', name: 'Jersey', nativeName: 'Jersey', region: 'Europe', flag: '🇯🇪', type: 'Territory' },
  { code: 'GG', name: 'Guernsey', nativeName: 'Guernsey', region: 'Europe', flag: '🇬🇬', type: 'Territory' },
  { code: 'IM', name: 'Isle of Man', nativeName: 'Isle of Man', region: 'Europe', flag: '🇮🇲', type: 'Territory' },
  { code: 'GI', name: 'Gibraltar', nativeName: 'Gibraltar', region: 'Europe', flag: '🇬🇮', type: 'Territory' },
  { code: 'FO', name: 'Faroe Islands', nativeName: 'Føroyar', region: 'Europe', flag: '🇫🇴', type: 'Territory' },
  { code: 'SJ', name: 'Svalbard and Jan Mayen', nativeName: 'Svalbard og Jan Mayen', region: 'Europe', flag: '🇸🇯', type: 'Territory' },

  // Middle East & Central Asia
  { code: 'SA', name: 'Saudi Arabia', nativeName: 'المملكة العربية السعودية', region: 'Middle East', flag: '🇸🇦' },
  { code: 'AE', name: 'United Arab Emirates', nativeName: 'الإمارات العربية المتحدة', region: 'Middle East', flag: '🇦🇪' },
  { code: 'IL', name: 'Israel', nativeName: 'ישראל', region: 'Middle East', flag: '🇮🇱' },
  { code: 'IR', name: 'Iran', nativeName: 'ایران', region: 'Middle East', flag: '🇮🇷' },
  { code: 'IQ', name: 'Iraq', nativeName: 'العراق', region: 'Middle East', flag: '🇮🇶' },
  { code: 'JO', name: 'Jordan', nativeName: 'الأردن', region: 'Middle East', flag: '🇯🇴' },
  { code: 'LB', name: 'Lebanon', nativeName: 'لبنان', region: 'Middle East', flag: '🇱🇧' },
  { code: 'QA', name: 'Qatar', nativeName: 'قطر', region: 'Middle East', flag: '🇶🇦' },
  { code: 'KW', name: 'Kuwait', nativeName: 'الكويت', region: 'Middle East', flag: '🇰🇼' },
  { code: 'OM', name: 'Oman', nativeName: 'عمان', region: 'Middle East', flag: '🇴🇲' },
  { code: 'BH', name: 'Bahrain', nativeName: 'البحرين', region: 'Middle East', flag: '🇧🇭' },
  { code: 'YE', name: 'Yemen', nativeName: 'اليمن', region: 'Middle East', flag: '🇾🇪' },
  { code: 'SY', name: 'Syria', nativeName: 'سوريا', region: 'Middle East', flag: '🇸🇾' },
  { code: 'PS', name: 'Palestine', nativeName: 'فلسطين', region: 'Middle East', flag: '🇵🇸', type: 'Disputed' },
  { code: 'KZ', name: 'Kazakhstan', nativeName: 'Қазақстан', region: 'Central Asia', flag: '🇰🇿' },
  { code: 'UZ', name: 'Uzbekistan', nativeName: 'Oʻzbekiston', region: 'Central Asia', flag: '🇺🇿' },
  { code: 'TM', name: 'Turkmenistan', nativeName: 'Türkmenistan', region: 'Central Asia', flag: '🇹🇲' },
  { code: 'TJ', name: 'Tajikistan', nativeName: 'Тоҷикистон', region: 'Central Asia', flag: '🇹🇯' },
  { code: 'KG', name: 'Kyrgyzstan', nativeName: 'Кыргызстан', region: 'Central Asia', flag: '🇰🇬' },
  { code: 'GE', name: 'Georgia', nativeName: 'საქართველო', region: 'Caucasus', flag: '🇬🇪' },
  { code: 'AM', name: 'Armenia', nativeName: 'Հայաստան', region: 'Caucasus', flag: '🇦🇲' },
  { code: 'AZ', name: 'Azerbaijan', nativeName: 'Azərbaycan', region: 'Caucasus', flag: '🇦🇿' },

  // Africa
  { code: 'EG', name: 'Egypt', nativeName: 'مصر', region: 'Africa', flag: '🇪🇬' },
  { code: 'ZA', name: 'South Africa', nativeName: 'South Africa', region: 'Africa', flag: '🇿🇦' },
  { code: 'NG', name: 'Nigeria', nativeName: 'Nigeria', region: 'Africa', flag: '🇳🇬' },
  { code: 'KE', name: 'Kenya', nativeName: 'Kenya', region: 'Africa', flag: '🇰🇪' },
  { code: 'ET', name: 'Ethiopia', nativeName: 'ኢትዮጵያ', region: 'Africa', flag: '🇪🇹' },
  { code: 'MA', name: 'Morocco', nativeName: 'المغرب', region: 'Africa', flag: '🇲🇦' },
  { code: 'DZ', name: 'Algeria', nativeName: 'الجزائر', region: 'Africa', flag: '🇩🇿' },
  { code: 'TN', name: 'Tunisia', nativeName: 'تونس', region: 'Africa', flag: '🇹🇳' },
  { code: 'LY', name: 'Libya', nativeName: 'ليبيا', region: 'Africa', flag: '🇱🇾' },
  { code: 'SD', name: 'Sudan', nativeName: 'السودان', region: 'Africa', flag: '🇸🇩' },
  { code: 'GH', name: 'Ghana', nativeName: 'Ghana', region: 'Africa', flag: '🇬🇭' },
  { code: 'CI', name: 'Ivory Coast', nativeName: 'Côte d\'Ivoire', region: 'Africa', flag: '🇨🇮' },
  { code: 'SN', name: 'Senegal', nativeName: 'Sénégal', region: 'Africa', flag: '🇸🇳' },
  { code: 'TZ', name: 'Tanzania', nativeName: 'Tanzania', region: 'Africa', flag: '🇹🇿' },
  { code: 'UG', name: 'Uganda', nativeName: 'Uganda', region: 'Africa', flag: '🇺🇬' },
  { code: 'ZM', name: 'Zambia', nativeName: 'Zambia', region: 'Africa', flag: '🇿🇲' },
  { code: 'ZW', name: 'Zimbabwe', nativeName: 'Zimbabwe', region: 'Africa', flag: '🇿🇼' },
  { code: 'AO', name: 'Angola', nativeName: 'Angola', region: 'Africa', flag: '🇦🇴' },
  { code: 'MZ', name: 'Mozambique', nativeName: 'Moçambique', region: 'Africa', flag: '🇲🇿' },
  { code: 'MG', name: 'Madagascar', nativeName: 'Madagasikara', region: 'Africa', flag: '🇲🇬' },
  { code: 'CM', name: 'Cameroon', nativeName: 'Cameroun', region: 'Africa', flag: '🇨🇲' },
  { code: 'CD', name: 'DR Congo', nativeName: 'RD Congo', region: 'Africa', flag: '🇨🇩' },
  { code: 'CG', name: 'Congo', nativeName: 'Congo', region: 'Africa', flag: '🇨🇬' },
  { code: 'GA', name: 'Gabon', nativeName: 'Gabon', region: 'Africa', flag: '🇬🇦' },
  { code: 'ML', name: 'Mali', nativeName: 'Mali', region: 'Africa', flag: '🇲🇱' },
  { code: 'BF', name: 'Burkina Faso', nativeName: 'Burkina Faso', region: 'Africa', flag: '🇧🇫' },
  { code: 'NE', name: 'Niger', nativeName: 'Niger', region: 'Africa', flag: '🇳🇪' },
  { code: 'TD', name: 'Chad', nativeName: 'Tchad', region: 'Africa', flag: '🇹🇩' },
  { code: 'CF', name: 'Central African Republic', nativeName: 'République centrafricaine', region: 'Africa', flag: '🇨🇫' },
  { code: 'SS', name: 'South Sudan', nativeName: 'South Sudan', region: 'Africa', flag: '🇸🇸' },
  { code: 'SO', name: 'Somalia', nativeName: 'Soomaaliya', region: 'Africa', flag: '🇸🇴' },
  { code: 'DJ', name: 'Djibouti', nativeName: 'Djibouti', region: 'Africa', flag: '🇩🇯' },
  { code: 'ER', name: 'Eritrea', nativeName: 'ኤርትራ', region: 'Africa', flag: '🇪🇷' },
  { code: 'RW', name: 'Rwanda', nativeName: 'Rwanda', region: 'Africa', flag: '🇷🇼' },
  { code: 'BI', name: 'Burundi', nativeName: 'Burundi', region: 'Africa', flag: '🇧🇮' },
  { code: 'MW', name: 'Malawi', nativeName: 'Malawi', region: 'Africa', flag: '🇲🇼' },
  { code: 'NA', name: 'Namibia', nativeName: 'Namibia', region: 'Africa', flag: '🇳🇦' },
  { code: 'BW', name: 'Botswana', nativeName: 'Botswana', region: 'Africa', flag: '🇧🇼' },
  { code: 'LS', name: 'Lesotho', nativeName: 'Lesotho', region: 'Africa', flag: '🇱🇸' },
  { code: 'SZ', name: 'Eswatini', nativeName: 'Eswatini', region: 'Africa', flag: '🇸🇿' },
  { code: 'MU', name: 'Mauritius', nativeName: 'Mauritius', region: 'Africa', flag: '🇲🇺' },
  { code: 'SC', name: 'Seychelles', nativeName: 'Seychelles', region: 'Africa', flag: '🇸🇨' },
  { code: 'KM', name: 'Comoros', nativeName: 'Comores', region: 'Africa', flag: '🇰🇲' },
  { code: 'CV', name: 'Cape Verde', nativeName: 'Cabo Verde', region: 'Africa', flag: '🇨🇻' },
  { code: 'ST', name: 'Sao Tome and Principe', nativeName: 'São Tomé e Príncipe', region: 'Africa', flag: '🇸🇹' },
  { code: 'GQ', name: 'Equatorial Guinea', nativeName: 'Guinea Ecuatorial', region: 'Africa', flag: '🇬🇶' },
  { code: 'GN', name: 'Guinea', nativeName: 'Guinée', region: 'Africa', flag: '🇬🇳' },
  { code: 'GW', name: 'Guinea-Bissau', nativeName: 'Guiné-Bissau', region: 'Africa', flag: '🇬🇼' },
  { code: 'SL', name: 'Sierra Leone', nativeName: 'Sierra Leone', region: 'Africa', flag: '🇸🇱' },
  { code: 'LR', name: 'Liberia', nativeName: 'Liberia', region: 'Africa', flag: '🇱🇷' },
  { code: 'BJ', name: 'Benin', nativeName: 'Bénin', region: 'Africa', flag: '🇧🇯' },
  { code: 'TG', name: 'Togo', nativeName: 'Togo', region: 'Africa', flag: '🇹🇬' },
  { code: 'MR', name: 'Mauritania', nativeName: 'Mauritanie', region: 'Africa', flag: '🇲🇷' },
  { code: 'GM', name: 'Gambia', nativeName: 'Gambia', region: 'Africa', flag: '🇬🇲' },
  { code: 'RE', name: 'Réunion', nativeName: 'La Réunion', region: 'Africa', flag: '🇷🇪', type: 'Territory' },
  { code: 'YT', name: 'Mayotte', nativeName: 'Mayotte', region: 'Africa', flag: '🇾🇹', type: 'Territory' },
  { code: 'SH', name: 'Saint Helena', nativeName: 'Saint Helena', region: 'Africa', flag: '🇸🇭', type: 'Territory' },
  { code: 'AC', name: 'Ascension Island', nativeName: 'Ascension Island', region: 'Africa', flag: '🇦🇨', type: 'Territory' },
  { code: 'TA', name: 'Tristan da Cunha', nativeName: 'Tristan da Cunha', region: 'Africa', flag: '🇹🇦', type: 'Territory' },
  { code: 'EH', name: 'Western Sahara', nativeName: 'الصحراء الغربية', region: 'Africa', flag: '🇪🇭', type: 'Disputed' },

  // Oceania
  { code: 'AU', name: 'Australia', nativeName: 'Australia', region: 'Oceania', flag: '🇦🇺' },
  { code: 'NZ', name: 'New Zealand', nativeName: 'New Zealand', region: 'Oceania', flag: '🇳🇿' },
  { code: 'FJ', name: 'Fiji', nativeName: 'Fiji', region: 'Oceania', flag: '🇫🇯' },
  { code: 'PG', name: 'Papua New Guinea', nativeName: 'Papua New Guinea', region: 'Oceania', flag: '🇵🇬' },
  { code: 'SB', name: 'Solomon Islands', nativeName: 'Solomon Islands', region: 'Oceania', flag: '🇸🇧' },
  { code: 'VU', name: 'Vanuatu', nativeName: 'Vanuatu', region: 'Oceania', flag: '🇻🇺' },
  { code: 'WS', name: 'Samoa', nativeName: 'Samoa', region: 'Oceania', flag: '🇼🇸' },
  { code: 'TO', name: 'Tonga', nativeName: 'Tonga', region: 'Oceania', flag: '🇹🇴' },
  { code: 'KI', name: 'Kiribati', nativeName: 'Kiribati', region: 'Oceania', flag: '🇰🇮' },
  { code: 'MH', name: 'Marshall Islands', nativeName: 'Marshall Islands', region: 'Oceania', flag: '🇲🇭' },
  { code: 'FM', name: 'Micronesia', nativeName: 'Micronesia', region: 'Oceania', flag: '🇫🇲' },
  { code: 'PW', name: 'Palau', nativeName: 'Palau', region: 'Oceania', flag: '🇵🇼' },
  { code: 'NR', name: 'Nauru', nativeName: 'Nauru', region: 'Oceania', flag: '🇳🇷' },
  { code: 'TV', name: 'Tuvalu', nativeName: 'Tuvalu', region: 'Oceania', flag: '🇹🇻' },
  { code: 'CK', name: 'Cook Islands', nativeName: 'Cook Islands', region: 'Oceania', flag: '🇨🇰', type: 'Autonomous' },
  { code: 'NU', name: 'Niue', nativeName: 'Niue', region: 'Oceania', flag: '🇳🇺', type: 'Autonomous' },
  { code: 'NC', name: 'New Caledonia', nativeName: 'Nouvelle-Calédonie', region: 'Oceania', flag: '🇳🇨', type: 'Territory' },
  { code: 'PF', name: 'French Polynesia', nativeName: 'Polynésie française', region: 'Oceania', flag: '🇵🇫', type: 'Territory' },
  { code: 'WF', name: 'Wallis and Futuna', nativeName: 'Wallis-et-Futuna', region: 'Oceania', flag: '🇼🇫', type: 'Territory' },
  { code: 'AS', name: 'American Samoa', nativeName: 'American Samoa', region: 'Oceania', flag: '🇦🇸', type: 'Territory' },
  { code: 'GU', name: 'Guam', nativeName: 'Guam', region: 'Oceania', flag: '🇬🇺', type: 'Territory' },
  { code: 'MP', name: 'Northern Mariana Islands', nativeName: 'Northern Mariana Islands', region: 'Oceania', flag: '🇲🇵', type: 'Territory' },
  { code: 'CX', name: 'Christmas Island', nativeName: 'Christmas Island', region: 'Oceania', flag: '🇨🇽', type: 'Territory' },
  { code: 'CC', name: 'Cocos (Keeling) Islands', nativeName: 'Cocos (Keeling) Islands', region: 'Oceania', flag: '🇨🇨', type: 'Territory' },
  { code: 'NF', name: 'Norfolk Island', nativeName: 'Norfolk Island', region: 'Oceania', flag: '🇳🇫', type: 'Territory' },
  { code: 'TK', name: 'Tokelau', nativeName: 'Tokelau', region: 'Oceania', flag: '🇹🇰', type: 'Territory' },
  { code: 'PN', name: 'Pitcairn Islands', nativeName: 'Pitcairn Islands', region: 'Oceania', flag: '🇵🇳', type: 'Territory' },
  { code: 'IO', name: 'British Indian Ocean Territory', nativeName: 'British Indian Ocean Territory', region: 'Africa', flag: '🇮🇴', type: 'Territory' },
  { code: 'TF', name: 'French Southern and Antarctic Lands', nativeName: 'TAAF', region: 'Africa', flag: '🇹🇫', type: 'Territory' },
  { code: 'SBA', name: 'Sovereign Base Areas', nativeName: 'Akrotiri and Dhekelia', region: 'Europe', flag: '🇨🇾', type: 'Territory' },
  { code: 'AQ', name: 'Antarctica', nativeName: 'Antarctica', region: 'Antarctica', flag: '🇦🇶', type: 'Special' },

  // Disputed & Special Territories
  { code: 'XK', name: 'Kosovo', nativeName: 'Kosovë', region: 'Europe', flag: '🇽🇰', type: 'Disputed' },
  { code: 'BT_T', name: 'Bir Tawil', nativeName: 'بير طويل', region: 'Africa', flag: '🏳️', type: 'Disputed' },
  { code: 'CRIM', name: 'Crimea', nativeName: 'Крим', region: 'Europe', flag: '🇷🇺/🇺🇦', type: 'Disputed' },
  { code: 'DONB', name: 'Donbas', nativeName: 'Донбас', region: 'Europe', flag: '🇷🇺/🇺🇦', type: 'Disputed' },
  { code: 'KASH', name: 'Kashmir', nativeName: 'Kashmir', region: 'South Asia', flag: '🇮🇳/🇵🇰', type: 'Disputed' },
  { code: 'SCSD', name: 'South China Sea Islands', nativeName: '南中国海', region: 'Southeast Asia', flag: '🏳️', type: 'Disputed' },
  { code: 'EEBD', name: 'Ethiopia-Eritrea Border', nativeName: 'Border', region: 'Africa', flag: '🇪🇹/🇪🇷', type: 'Disputed' },
  { code: 'TRNC', name: 'Northern Cyprus', nativeName: 'Kuzey Kıbrıs', region: 'Europe', flag: '🇹🇷', type: 'Disputed' },
  { code: 'SLND', name: 'Somaliland', nativeName: 'Soomaaliland', region: 'Africa', flag: '🇸🇴', type: 'Disputed' },
  { code: 'PMR', name: 'Transnistria', nativeName: 'Приднестровье', region: 'Europe', flag: '🇲🇩', type: 'Disputed' },
  { code: 'PHIS', name: 'Pheasant Island', nativeName: 'Île de la Conférence', region: 'Europe', flag: '🇫🇷/🇪🇸', type: 'Special' },
  { code: 'BAAR', name: 'Baarle', nativeName: 'Baarle', region: 'Europe', flag: '🇧🇪/🇳🇱', type: 'Special' },
  { code: 'CYGL', name: 'UN Buffer Zone (Cyprus)', nativeName: 'Green Line', region: 'Europe', flag: '🇺🇳', type: 'Special' },
];
